DROP DATABASE IF EXISTS employees;
CREATE DATABASE employees;

USE employees;

CREATE TABLE department (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR (30) NOT NULL
);

CREATE TABLE role (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR (30) NOT NULL,
    salary DECIMAL(8,2),
    department_id INT
);

CREATE TABLE employees (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INT NOT NULL,
    manager_id INT
);

